name: config
experiment_env:

  # model_parameters
  nl_embed_size                   : [128]
  action_embed_size               : [128]
  hidden_size                     : [256]
  att_size                        : [256]
  field_embed_size                : [64]
  type_embed_size                 : [64]
  cardinality_embed_size          : [16]
  dropout_encoder                 : [0]
  dropout_decoder                 : [0.4]
  model                           : "seq2seq"
  n_layers                        : 1
  beam_size                       : 1
  lr                              : 0.001
  lr_decay                        : 0.0001
  lr_decay_after_epoch            : 50
  max_num_trial                   : 5
  patience                        : 3
  readout                         : "identity"
  query_vec_to_action_diff_map    : False
  primitive_token_label_smoothing : 0.0
  len_max                         : 150
  copy                            : True
  glove                           : False
  parent_feeding_field            : False
  parent_feeding_type             : False

  # dataset_parameters
  dataset                         : "conala"
  mode                            : "train"
  train                           : True
  test                            : True
  number_merge_ex                 : 0
  create_vocab                    : True
  word_freq                       : 1
  metric                          : 'BLEU'
  change_term_name                : False

  # train_parameters
  batch_size                      : 128
  epochs                          : 80
  log_every                       : 5
  seed                            : 1234
  GPU                             : 1